### ISSUE TITLE
Portable version of Adora

### ISSUE THREAD

**Issue by shujaatak** [hash1018/Adora#1]
It's highly recommended to create portable version of Adora as it is in initial testing stage.

**Comment by shujaatak** [comment]
Portable version can be a simple zip file containing Adora's exe file and required libraries etc.

**Comment by hash1018** [comment]
Okay I will do it as you requested

**Comment by hash1018** [comment]
> Portable version can be a simple zip file containing Adora's exe file and required libraries etc.

added zip file which contains exe, required libraries and etc.
