### ISSUE TITLE
Can't choose drawing tool once I have already chosen one.

### ISSUE THREAD

**Issue by shujaatak** [hash1018/Adora#5]
I noticed that I can't select a new tool after I select a tool, for example a pencil tool.

The workaround I use is that I select the Recording Window from the Windows Toolbar and this then enable all tools in the Recording Window and allow me to select some other tool like Line Tool etc.

**Comment by hash1018** [comment]
This is because your drawing tool (actually it is called control box) is below recording window

**Comment by shujaatak** [comment]
> This is because your drawing tool (actually it is called control box) is below recording window

That's correct! and that's what I thought is the issue as it creates confusion.

**Comment by hash1018** [comment]
you know, at this issue, how can I reduce confusion? 

Actually, when I select pencil, line or etc, the recording window has transparent layer where mouse can click and draw them.

So in this case, recording window has to have focus and the level of it has to be above the control box.

**Comment by shujaatak** [comment]
I think this will work:
Show the Recording Window at the top as soon as the user stops using the tool and make the Drawing Window at the top when user starts using the tool.
Let suppose a user was drawing lines with pencil tool selected then as soon as he stops drawing(left mouse button up) then bring the Recording Window again in the front so that if the user want to select an another tool then he could do so.

**Comment by hash1018** [comment]
> I think this will work:
> Show the Recording Window at the top as soon as the user stops using the tool and make the Drawing Window at the top when user starts using the tool.
> Let suppose a user was drawing lines with pencil tool selected then as soon as he stops drawing(left mouse button up) then bring the Recording Window again in the front so that if the user want to select an another tool then he could do so.

Oh!!!!! Great idea. I have never thought about it.

I am going to apply it as you said. By the way I really appreciate your efforts.

**Comment by hash1018** [comment]
just Applied it.
